import { NextResponse } from "next/server";

import { handleApiError } from "@/lib/api-errors";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const [
      stationCount,
      aircraftCount,
      crewMemberCount,
      flightCount,
      aircraftCrewAssignmentCount,
      activeAlertCount,
      operatorCount,
      operatingAuthorityCount,
      operationalControlRecordCount,
      flightReleaseCount,
      tripOrMissionCount,
      flightLegCount,
      aircraftAssignmentCount,
      crewLegAssignmentCount,
      turnaroundLinkCount,
      manifestCount,
      manifestItemCount,
      weightBalanceRunCount,
      flightLocatingRecordCount,
      positionReportCount,
      dispatchPackageCount,
      weatherBriefingSnapshotCount,
      notamSnapshotCount,
      flightPlanReferenceCount,
      aircraftConfigurationCount,
      aircraftCapabilityCount,
      discrepancyCount,
      deferralCount,
      maintenanceEventCount,
      airworthinessReleaseCount,
      releasePolicyProfileCount,
      releasePolicyRuleCount,
      releaseReadinessSnapshotCount,
      releaseReadinessFindingCount,
      releaseOverrideCount,
      releaseAuditEventCount,
      releasePackageCount,
      releasePackageEvidenceLinkCount,
      importBatchCount,
      importSourceCount,
      importStagingRowCount,
      importValidationFindingCount,
      importMappingDecisionCount,
      crewSchedulePeriodCount,
      crewScheduleRequestCount,
      crewRotationPatternCount,
      crewRotationPatternDayCount,
      crewScheduleEntryCount,
      crewCertificateCount,
      crewMedicalCount,
      crewTrainingEventCount,
      crewCheckEventCount,
      crewRecencyEventCount,
      crewDutyPeriodCount,
      crewRestPeriodCount,
      dutyRestPolicyProfileCount,
      dutyRestRuleSettingCount,
      crewLocationRecordCount,
      crewLogisticsNeedCount,
      userPasswordCredentialCount,
      userSessionCount,
    ] = await Promise.all([
      prisma.station.count(),
      prisma.aircraft.count(),
      prisma.crewMember.count(),
      prisma.flight.count(),
      prisma.aircraftCrewAssignment.count(),
      prisma.alert.count({ where: { status: "ACTIVE" } }),
      prisma.operator.count(),
      prisma.operatingAuthority.count(),
      prisma.operationalControlRecord.count(),
      prisma.flightRelease.count(),
      prisma.tripOrMission.count(),
      prisma.flightLeg.count(),
      prisma.aircraftAssignment.count(),
      prisma.crewLegAssignment.count(),
      prisma.turnaroundLink.count(),
      prisma.manifest.count(),
      prisma.manifestItem.count(),
      prisma.weightBalanceRun.count(),
      prisma.flightLocatingRecord.count(),
      prisma.positionReport.count(),
      prisma.dispatchPackage.count(),
      prisma.weatherBriefingSnapshot.count(),
      prisma.notamSnapshot.count(),
      prisma.flightPlanReference.count(),
      prisma.aircraftConfiguration.count(),
      prisma.aircraftCapability.count(),
      prisma.discrepancy.count(),
      prisma.deferral.count(),
      prisma.maintenanceEvent.count(),
      prisma.airworthinessRelease.count(),
      prisma.releasePolicyProfile.count(),
      prisma.releasePolicyRule.count(),
      prisma.releaseReadinessSnapshot.count(),
      prisma.releaseReadinessFinding.count(),
      prisma.releaseOverride.count(),
      prisma.releaseAuditEvent.count(),
      prisma.releasePackage.count(),
      prisma.releasePackageEvidenceLink.count(),
      prisma.importBatch.count(),
      prisma.importSource.count(),
      prisma.importStagingRow.count(),
      prisma.importValidationFinding.count(),
      prisma.importMappingDecision.count(),
      prisma.crewSchedulePeriod.count(),
      prisma.crewScheduleRequest.count(),
      prisma.crewRotationPattern.count(),
      prisma.crewRotationPatternDay.count(),
      prisma.crewScheduleEntry.count(),
      prisma.crewCertificate.count(),
      prisma.crewMedical.count(),
      prisma.crewTrainingEvent.count(),
      prisma.crewCheckEvent.count(),
      prisma.crewRecencyEvent.count(),
      prisma.crewDutyPeriod.count(),
      prisma.crewRestPeriod.count(),
      prisma.dutyRestPolicyProfile.count(),
      prisma.dutyRestRuleSetting.count(),
      prisma.crewLocationRecord.count(),
      prisma.crewLogisticsNeed.count(),
      prisma.userPasswordCredential.count(),
      prisma.userSession.count(),
    ]);

    return NextResponse.json({
      ok: true,
      database: "connected",
      counts: {
        stations: stationCount,
        aircraft: aircraftCount,
        crewMembers: crewMemberCount,
        flights: flightCount,
        aircraftCrewAssignments: aircraftCrewAssignmentCount,
        activeAlerts: activeAlertCount,
        operators: operatorCount,
        operatingAuthorities: operatingAuthorityCount,
        operationalControlRecords: operationalControlRecordCount,
        flightReleases: flightReleaseCount,
        tripOrMissions: tripOrMissionCount,
        flightLegs: flightLegCount,
        aircraftAssignments: aircraftAssignmentCount,
        crewLegAssignments: crewLegAssignmentCount,
        turnaroundLinks: turnaroundLinkCount,
        manifests: manifestCount,
        manifestItems: manifestItemCount,
        weightBalanceRuns: weightBalanceRunCount,
        flightLocatingRecords: flightLocatingRecordCount,
        positionReports: positionReportCount,
        dispatchPackages: dispatchPackageCount,
        weatherBriefingSnapshots: weatherBriefingSnapshotCount,
        notamSnapshots: notamSnapshotCount,
        flightPlanReferences: flightPlanReferenceCount,
        aircraftConfigurations: aircraftConfigurationCount,
        aircraftCapabilities: aircraftCapabilityCount,
        discrepancies: discrepancyCount,
        deferrals: deferralCount,
        maintenanceEvents: maintenanceEventCount,
        airworthinessReleases: airworthinessReleaseCount,
        releasePolicyProfiles: releasePolicyProfileCount,
        releasePolicyRules: releasePolicyRuleCount,
        releaseReadinessSnapshots: releaseReadinessSnapshotCount,
        releaseReadinessFindings: releaseReadinessFindingCount,
        releaseOverrides: releaseOverrideCount,
        releaseAuditEvents: releaseAuditEventCount,
        releasePackages: releasePackageCount,
        releasePackageEvidenceLinks: releasePackageEvidenceLinkCount,
        importBatches: importBatchCount,
        importSources: importSourceCount,
        importStagingRows: importStagingRowCount,
        importValidationFindings: importValidationFindingCount,
        importMappingDecisions: importMappingDecisionCount,
        crewSchedulePeriods: crewSchedulePeriodCount,
        crewScheduleRequests: crewScheduleRequestCount,
        crewRotationPatterns: crewRotationPatternCount,
        crewRotationPatternDays: crewRotationPatternDayCount,
        crewScheduleEntries: crewScheduleEntryCount,
        crewCertificates: crewCertificateCount,
        crewMedicals: crewMedicalCount,
        crewTrainingEvents: crewTrainingEventCount,
        crewCheckEvents: crewCheckEventCount,
        crewRecencyEvents: crewRecencyEventCount,
        crewDutyPeriods: crewDutyPeriodCount,
        crewRestPeriods: crewRestPeriodCount,
        dutyRestPolicyProfiles: dutyRestPolicyProfileCount,
        dutyRestRuleSettings: dutyRestRuleSettingCount,
        crewLocationRecords: crewLocationRecordCount,
        crewLogisticsNeeds: crewLogisticsNeedCount,
        userPasswordCredentials: userPasswordCredentialCount,
        userSessions: userSessionCount,
      },
    });
  } catch (error) {
    return handleApiError(error);
  }
}
